# Generated by Django 5.2.6 on 2025-11-03 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmembers', '0003_alter_churchmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='age_group',
            field=models.CharField(choices=[('youth', 'Youth'), ('men', 'Men'), ('women', 'Women'), ('children', 'Children')], db_column='age_group', default='men', max_length=20),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='first_name',
            field=models.CharField(db_column='first_name', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='last_name',
            field=models.CharField(db_column='last_name', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='branch_name',
            field=models.CharField(db_column='branch_name', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='churchmember', to=settings.AUTH_USER_MODEL),
        ),
    ]
