# Generated by Django 5.2.6 on 2025-11-02 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchsecretary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchsecretary',
            options={'verbose_name': 'Branch Secretary', 'verbose_name_plural': 'Branch Secretaries'},
        ),
        migrations.RemoveField(
            model_name='branchsecretary',
            name='user',
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='age_group',
            field=models.CharField(choices=[('youth', 'Youth'), ('men', 'Men'), ('women', 'Women'), ('children', 'Children')], default='men', max_length=20),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='branch_name',
            field=models.CharField(blank=True, default='Unknown Branch', max_length=100),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='church_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_secretary_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='is_baptized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='last_name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='married', max_length=20),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='resident',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='branchsecretary',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterModelTable(
            name='branchsecretary',
            table='branch_secretary',
        ),
    ]
