# Generated by Django 5.2.6 on 2025-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('salary_wages', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('utilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('visitation_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('electricity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transportation', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('communication', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('publicity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('medicals', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('instrument', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('donations', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('maintenance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church Expense',
                'verbose_name_plural': 'Church Expenses',
                'db_table': 'church_expenses',
                'ordering': ['-date'],
            },
        ),
    ]
