# Generated by Django 5.2.6 on 2025-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchexpenses',
            name='branch_name',
            field=models.CharField(blank=True, default='Unknown Branch', max_length=100),
        ),
    ]
