# Generated by Django 5.2.6 on 2025-11-05 03:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Unknown', max_length=100)),
                ('last_name', models.CharField(default='Pastor', max_length=100)),
                ('email_address', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('age_group', models.CharField(choices=[('youth', 'Youth'), ('men', 'Men'), ('women', 'Women'), ('children', 'Children')], default='men', max_length=20)),
                ('branch_name', models.CharField(blank=True, default='Unknown Branch', max_length=100)),
                ('resident', models.CharField(blank=True, default='', max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='married', max_length=20)),
                ('is_baptized', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('church_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pastor',
            },
        ),
    ]
