# Generated by Django 5.2.6 on 2025-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('speaker', models.CharField(max_length=100)),
                ('activity_name', models.CharField(max_length=150)),
                ('men_attendance', models.PositiveIntegerField(default=0)),
                ('women_attendance', models.PositiveIntegerField(default=0)),
                ('youth_attendance', models.PositiveIntegerField(default=0)),
                ('children_attendance', models.PositiveIntegerField(default=0)),
                ('general_offering', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_offering', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity Tracking',
                'verbose_name_plural': 'Activity Tracking',
                'db_table': 'activity_tracking',
                'ordering': ['-activity_date'],
            },
        ),
    ]
