# Generated by Django 5.2.6 on 2025-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytracking',
            name='branch_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
