# Generated by Django 5.2.6 on 2025-11-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchsecretary', '0002_alter_branchsecretary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchsecretary',
            options={},
        ),
    ]
