# Generated by Django 5.2.6 on 2025-10-31 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TitheReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tithe_date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tithe_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tithe Return',
                'verbose_name_plural': 'Tithe Returns',
                'db_table': 'tithe_returns',
                'ordering': ['-tithe_date'],
            },
        ),
    ]
