# Generated by Django 5.2.6 on 2025-11-03 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tithe_returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tithereturn',
            options={},
        ),
        migrations.RemoveField(
            model_name='tithereturn',
            name='day',
        ),
        migrations.AddField(
            model_name='tithereturn',
            name='branch_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tithereturn',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_tithes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tithereturn',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tithes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='tithereturn',
            table='tithe_return',
        ),
    ]
