# Generated by Django 5.2.6 on 2025-11-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='age_group',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='branch_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='email_address',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='gender',
            field=models.CharField(default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='is_baptized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='marital_status',
            field=models.CharField(default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='resident',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='whatsapp_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
