# Generated by Django 5.2.6 on 2025-11-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmembers', '0002_churchmember_age_group_churchmember_branch_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchmember',
            options={},
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='is_baptized',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='churchmember',
            name='whatsapp_number',
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='churchmember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='churchmember',
            table='church_member',
        ),
    ]
