# Generated by Django 5.2.6 on 2025-10-30 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchuser',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='otprecord',
            name='user',
        ),
        migrations.AddField(
            model_name='churchuser',
            name='branch_name',
            field=models.CharField(choices=[('Tanokrom', 'Tanokrom'), ('Kwesimintsim', 'Kwesimintsim'), ('Shama', 'Shama'), ('Assakae', 'Assakae')], default='Tanokrom', max_length=20),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='otp_is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='churchuser',
            name='otp_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='OTPRecord',
        ),
    ]
