# Generated by Django 5.2.6 on 2025-11-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_churchexpenses_branch_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('salary_wages', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maintenance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('evangelism', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('welfare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('projects', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('branch_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense',
            },
        ),
        migrations.DeleteModel(
            name='ChurchExpenses',
        ),
    ]
