# Generated by Django 5.2.6 on 2025-11-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitytracking_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytracking',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
    ]
