# Generated by Django 5.2.6 on 2025-11-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activitytracking_branch_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytracking',
            options={},
        ),
        migrations.AddField(
            model_name='activitytracking',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitytracking',
            name='total_offering',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='activitytracking',
            name='activity_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activitytracking',
            name='children_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitytracking',
            name='men_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitytracking',
            name='speaker',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitytracking',
            name='women_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitytracking',
            name='youth_attendance',
            field=models.IntegerField(default=0),
        ),
    ]
